config_filename: "logstash.conf"
config_path: "/etc/logstash/conf.d"
logstash_file_path: "/home/vagrant/access_log"
logstash_file_position: "beginning"
logstash_elasticsearch_server: "localhost:9200"
filter_plugin_grok_match_field: "message"
filter_plugin_grok_match_value: "%{COMBINEDAPACHELOG}" 
filter_plugin_date_field: "timestamp"
filter_plugin_date_format: "dd/MMM/yyyy:HH:mm:ss Z"
output_stdout: "rubydebug"