---
- name: 'Install ElasticSearch'
  apt:
    name: elasticsearch
    update_cache: yes
    cache_valid_time: 3600
    state: latest
  become: yes

- name: 'Setting up ElasticSearch'
  template:
    src: "{{ config_filename }}.j2"
    dest: "{{ config_path }}/{{ config_filename }}"
    backup: yes
  become: yes
  notify:
    - daemon reload
    - enable elasticsearch
    - start elasticsearch
